apiVersion: v1
kind: Pod
metadata:
  name: angular-app-test
  labels:
    app: angular-app
spec:
  containers:
  - name: angular-app-container
    image: nombre_de_la_imagen:test
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular-app-service-test
spec:
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
