apiVersion: v1
kind: Pod
metadata:
  name: angular-app-${BUILD_NUMBER}
  labels:
    app: angular-app
spec:
  containers:
  - name: angular-app-container
    image: nombre_de_la_imagen:${VERSION}.${BUILD_NUMBER}
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular-app-service-${BUILD_NUMBER}
spec:
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
